name: Generate Documentation

on:
  workflow_call:
    inputs:
      verify_tag:
        type: boolean

jobs:
  verify:
    runs-on: ubuntu-latest
 #  if: inputs.verify_tag == 'true'
    outputs:
      isValid: ${{ steps.version.outputs.is_valid }}
    steps:
      - uses: nowsprinting/check-version-format-action@v3.2.4
        id: version
  
  generate:
    runs-on: ubuntu-latest
 #  needs: [verify]
 #  if: needs.verify.outputs.isValid == 'true' || inputs.verify_tag == 'false'
    
    steps:
      # Prevents error when DocFX tries to look for index.md
      - run: git config --global core.symlinks false
      
      - uses: actions/checkout@v3
        
      - name: Generate Table of Contents
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module powershell-yaml, docfx-toc-generator
          
          cd Documentation~
          Build-TocHereRecursive
          
      - name: Build Documentation
        uses: nikeee/docfx-action@v1.0.0
        with:
          args: Documentation~/docfx.json
          
      - name: Publish Documentation on GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          folder: Documentation~/_site
